version: "3.7"
# Definição dos Serviços
services:
  # Definição do Serviço do Worker
  n8n_webhook:
    # imagem do docker
    # se possível, não use a latest .. deixe uma versão fixa
    # https://hub.docker.com/r/n8nio/n8n/tags
    image: n8nio/n8n:1.98.2
    # Define o hotname do container
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    # comando padrão para subir o servidor web
    command: webhook
    # configura a rede do serviço
    networks:
      - network_swarm_public
    # configura as variáveis de ambiente
    environment:
      #########################################################
      #########################################################
      # Configuração Gerais do N8N ############################
      #########################################################
      #########################################################
      # Gere uma nova chave aqui https://www.avast.com/random-password-generator#mac
      - N8N_ENCRYPTION_KEY=2rbDhlB7Bdc5SHr
      # Configura o ambiente de execução do N8N
      - NODE_ENV=production
      # Configura o Tamanho do Payload aceito pelo N8N (em MB)
      - N8N_PAYLOAD_SIZE_MAX=16
      # Configura o nível de log do N8N
      - N8N_LOG_LEVEL=info
      # Configura o Timezone do N8N
      - GENERIC_TIMEZONE=America/Sao_Paulo
      #########################################################
      #########################################################
      #########################################################
      # Configuração do Banco de Dados ########################
      #########################################################
      #########################################################
      #########################################################
      # Define o Tipo de Banco de Dados para Postgres
      - DB_TYPE=postgresdb
      # Configura o Nome do Banco de Dados
      - DB_POSTGRESDB_DATABASE=n8n
      # Configura o Host do Banco de Dados
      - DB_POSTGRESDB_HOST=postgres
      # Configura a Porta do Banco de Dados
      - DB_POSTGRESDB_PORT=5432
      # Configura o Usuário do Banco de Dados
      - DB_POSTGRESDB_USER=postgres
      # Configura a Senha do Banco de Dados
      - DB_POSTGRESDB_PASSWORD=476178274A35F347E33B74428EAB1
      #########################################################
      #########################################################
      #########################################################
      # Configuração do Endereço do N8N #######################
      #########################################################
      #########################################################
      #########################################################
      # Define a Porta http para o N8N (padrão: 5678)
      - N8N_PORT=5678
      # Configura o Host do Editor do N8N
      - N8N_HOST=editor.ckhub.com.br
      # Configura o Endereço competo do Editor (tem que deixar / no final)
      - N8N_EDITOR_BASE_URL=https://editor.ckhub.com.br/
      # Força o uso de SSL nas URL internas do N8N
      - N8N_PROTOCOL=https
      # Configura o Endereço do Webhook
      # Pode ser subdomínio ou outro domínio
      - WEBHOOK_URL=https://webhook.ckhub.com.br/
      #########################################################
      #########################################################
      #########################################################
      # Configuração da Modo de Execução do N8N (fila) ########
      #########################################################
      #########################################################
      #########################################################
      - EXECUTIONS_MODE=queue
      # Configura o host do Redis
      - QUEUE_BULL_REDIS_HOST=redis
      # Configura a porta do Redis
      - QUEUE_BULL_REDIS_PORT=6379
      # Configura o indice do banco de dados do Redis
      - QUEUE_BULL_REDIS_DB=2
      # Configura a senha do Redis (caso você use senha no redis)
      # - QUEUE_BULL_REDIS_PASSWORD=CNNT!noc@00#
      #########################################################
      #########################################################
      # Configuração da Manutenção e Limpeza do N8N ###########
      #########################################################
      #########################################################
      # Configura a limpeza dos dados de execução
      - EXECUTIONS_DATA_PRUNE=true
      # Configura o tempo máximo de armazenamento dos dados de execução
      - EXECUTIONS_DATA_MAX_AGE=336 # 2 semanas
      #########################################################
      #########################################################
      # Configuração de Bibliotecas do N8N ####################
      #########################################################
      #########################################################
      # Configura quais bibliotecas nativas podem ser importardas no node Code
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      # Configura as bibliotecas externas que serão utilizadas
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash
      # Habilita o uso de pacotes da comunidade
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      # Reinstalar os Community Nodes
      - N8N_REINSTALL_MISSING_PACKAGES=true
    # Configura o Modo de Deploy da Aplicação
    deploy:
      # O editor será executado no modo de replicação
      mode: replicated
      # Vamos ter apenas uma instância do editor
      replicas: 5
      # Configura o local de execução
      placement:
        # Você pode rodar o Editor no Manager mesmo pois usa poucos recursos
        constraints:
          - node.role == manager
          # - node.hostname == worker1
          # - node.labels.app == workers # nome do label: app, valor do label: workers
      resources:
        # Definição dos Limites de Recursos deste Serviço
        limits:
          # Define a quantidade de CPU para o N8N para evitar travamento do Host
          cpus: "1"
          # Define a quantidade de RAM para o N8N para evitar travamento do Host
          memory: 1024M
      # Define os Labels do Serviço
      labels:
        # Configura o Roteamento do Traefik
        - traefik.enable=true
        # Define o enderço do Webhook do N8N
        - traefik.http.routers.n8n_webhook.rule=Host(`webhook.ckhub.com.br`)
        # Redireciona o endereço para HTTPS
        - traefik.http.routers.n8n_webhook.entrypoints=websecure
        # Define o certificado SSL
        - traefik.http.routers.n8n_webhook.tls.certresolver=letsencryptresolver
        # Define o serviço do Webhook
        - traefik.http.routers.n8n_webhook.service=n8n_webhook
        # Define a porta do serviço do Webhook
        - traefik.http.services.n8n_webhook.loadbalancer.server.port=5678
        # Define o uso do Host Header
        - traefik.http.services.n8n_webhook.loadbalancer.passHostHeader=true
      # Configura o modo de atualização do serviço
      update_config:
        # Configura o paralelismo de atualização
        parallelism: 1
        # Configura o tempo de espera entre as atualizações
        delay: 30s
        # Configura a ação em caso de falha
        order: start-first
        # Configura a ação em caso de falha
        failure_action: rollback
networks:
  network_swarm_public:
    name: network_swarm_public
    external: true
